### ISSUE TITLE
Webgrind task is missing from public/ansible_developer_recipes

### ISSUE THREAD

**Issue by chrisjimallen** [Voronenko/lamp-box#2]
I've noticed that if you follow the steps at https://github.com/Voronenko/lamp-box#prepare, you will receive the following error:

`
fatal: [default]: FAILED! => {"failed": true, "reason": "Unable to retrieve file contents\nCould not find or access '/Users/chris/Sites/lamp-box/public/ansible_developer_recipes/vagrant/tasks_vagrant_php_webgrind.yml'"}`

This is due to a missing .yml file in the repo. Happy to do a PR if you wanted to remove it from deployment/vagrant.yml

**Comment by Voronenko** [comment]
True, will re-introduce that back, as quite useful tool from time to time.
